# Generated by Django 4.2.27 on 2026-01-13 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crownie', '0004_user_avatar_user_bio_user_discord_chat_points_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='requirements',
            new_name='custom_requirements',
        ),
        migrations.RenameField(
            model_name='quest',
            old_name='completed_at',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='quest',
            old_name='created_at',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='points',
        ),
        migrations.AddField(
            model_name='quest',
            name='badge_reward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='current_completions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quest',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='is_daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quest',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quest',
            name='max_completions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quest',
            name='quest_type',
            field=models.CharField(choices=[('social', 'Social Engagement'), ('discord', 'Discord Activity'), ('content', 'Content Creation'), ('referral', 'Referral'), ('daily', 'Daily Challenge'), ('special', 'Special Event')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quest',
            name='recurrence_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quest',
            name='reputation_reward',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quest',
            name='required_daily_login_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quest',
            name='required_discord_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quest',
            name='required_discord_voice_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quest',
            name='required_referrals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quest',
            name='required_twitter_follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quest',
            name='required_twitter_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quest',
            name='required_twitter_retweet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quest',
            name='token_reward',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='quest',
            name='xp_reward',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quest',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('epic', 'Epic')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserQuestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('claimed', 'Claimed'), ('failed', 'Failed'), ('expired', 'Expired')], default='not_started', max_length=20)),
                ('discord_messages_count', models.IntegerField(default=0)),
                ('discord_voice_minutes', models.IntegerField(default=0)),
                ('twitter_followed', models.BooleanField(default=False)),
                ('twitter_liked', models.BooleanField(default=False)),
                ('twitter_retweeted', models.BooleanField(default=False)),
                ('referrals_count', models.IntegerField(default=0)),
                ('daily_login_streak', models.IntegerField(default=0)),
                ('custom_progress', models.TextField(blank=True, default='{}')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('reputation_claimed', models.BooleanField(default=False)),
                ('tokens_claimed', models.BooleanField(default=False)),
                ('badge_claimed', models.BooleanField(default=False)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='crownie.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('user', 'quest')},
            },
        ),
        migrations.CreateModel(
            name='QuestCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reputation_earned', models.IntegerField(default=0)),
                ('tokens_earned', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('badge_earned', models.CharField(blank=True, max_length=100, null=True)),
                ('xp_earned', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='crownie.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_completions', to=settings.AUTH_USER_MODEL)),
                ('user_quest_progress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crownie.userquestprogress')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_login_date', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
