# Generated by Django 4.2.27 on 2026-01-13 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crownie', '0005_rename_requirements_quest_custom_requirements_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='dailystreak',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailystreak',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailystreak',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailystreak',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailystreak',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailystreak',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailystreak',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_login_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longest_login_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reputationlog',
            name='action',
            field=models.CharField(choices=[('signup', 'Sign Up'), ('daily_login', 'Daily Login'), ('discord_connect', 'Discord Connect'), ('discord_chat', 'Discord Chat'), ('quest_complete', 'Quest Complete'), ('engagement', 'Engagement'), ('social_verify', 'Social Verification'), ('referral', 'Referral')], max_length=50),
        ),
    ]
