# Generated by Django 4.2.27 on 2026-08-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crownie', '0006_alter_quest_options_dailystreak_friday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='discord_chat_points',
            field=models.FloatField(default=0),
        ),
    ]
